#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.6.0
# from Racc grammar file "".
#

require 'racc/parser.rb'
module ASMREPL
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    14,     8,     8,     3,    16,    26,    18,    17,    19,    32,
     4,     7,     7,    27,    28,     9,    10,    33,    34,     7,
    21,    22,    23,    24,    25,     7,    30,    31,    35,    36,
    37,    38,    39,    40 ]

racc_action_check = [
    10,     2,    10,     0,    10,    20,    10,    10,    10,    29,
     1,     2,    10,    20,    20,     4,     5,    29,    29,    14,
    15,    16,    17,    18,    19,    21,    27,    28,    30,    31,
    33,    34,    37,    38 ]

racc_action_pointer = [
   -10,    10,    -3,   nil,    15,    11,   nil,   nil,   nil,   nil,
    -2,   nil,   nil,   nil,     5,    18,    14,    15,    16,    17,
     2,    11,   nil,   nil,   nil,   nil,   nil,    22,    23,     6,
    25,    26,   nil,    26,    27,   nil,   nil,    29,    30,   nil,
   nil ]

racc_action_default = [
   -18,   -18,   -18,    -5,   -18,   -18,    -4,    -6,    -7,    41,
   -18,    -1,    -2,    -3,   -18,   -18,   -18,   -18,   -18,   -18,
   -18,   -18,   -14,   -15,   -16,   -17,    -8,   -18,   -18,   -18,
   -18,   -18,   -11,   -18,   -18,    -9,   -10,   -18,   -18,   -12,
   -13 ]

racc_goto_table = [
     5,     6,     1,     2,    13,    15,   nil,   nil,    12,    11,
   nil,   nil,    20,   nil,   nil,   nil,   nil,   nil,   nil,    29 ]

racc_goto_check = [
     3,     4,     1,     2,     5,     6,   nil,   nil,     3,     4,
   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,     3 ]

racc_goto_pointer = [
   nil,     2,     3,    -2,    -1,    -6,    -5 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 16, :_reduce_1,
  4, 16, :_reduce_2,
  4, 16, :_reduce_3,
  2, 16, :_reduce_4,
  1, 17, :_reduce_5,
  1, 18, :_reduce_6,
  1, 19, :_reduce_7,
  3, 20, :_reduce_8,
  5, 20, :_reduce_9,
  5, 20, :_reduce_10,
  4, 20, :_reduce_11,
  6, 20, :_reduce_12,
  6, 20, :_reduce_13,
  2, 21, :_reduce_14,
  2, 21, :_reduce_15,
  2, 21, :_reduce_16,
  2, 21, :_reduce_17 ]

racc_reduce_n = 18

racc_shift_n = 41

racc_token_table = {
  false => 0,
  :error => 1,
  :on_lbracket => 2,
  :on_rbracket => 3,
  :on_int => 4,
  :on_comma => 5,
  :qword => 6,
  :ptr => 7,
  :word => 8,
  :dword => 9,
  :byte => 10,
  :plus => 11,
  :minus => 12,
  :on_instruction => 13,
  :on_register => 14 }

racc_nt_base = 15

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "on_lbracket",
  "on_rbracket",
  "on_int",
  "on_comma",
  "qword",
  "ptr",
  "word",
  "dword",
  "byte",
  "plus",
  "minus",
  "on_instruction",
  "on_register",
  "$start",
  "command",
  "instruction",
  "register",
  "int",
  "memory",
  "memsize" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

def _reduce_1(val, _values, result)
 result = new_command(val[0], val[1], val[3])
    result
end

def _reduce_2(val, _values, result)
 result = new_command(val[0], val[1], val[3])
    result
end

def _reduce_3(val, _values, result)
 result = new_command(val[0], val[1], val[3])
    result
end

def _reduce_4(val, _values, result)
 result = new_tuple(val[0], val[1])
    result
end

def _reduce_5(val, _values, result)
 result = [:instruction, val[0]]
    result
end

def _reduce_6(val, _values, result)
 result = [:register, val[0]]
    result
end

def _reduce_7(val, _values, result)
 result = [:int, Integer(val[0])]
    result
end

def _reduce_8(val, _values, result)
 result = [:memory, Fisk::M64.new(val[1].last, 0)]
    result
end

def _reduce_9(val, _values, result)
 result = [:memory, Fisk::M64.new(val[1].last, Integer(val[3]))]
    result
end

def _reduce_10(val, _values, result)
 result = [:memory, Fisk::M64.new(val[1].last, -Integer(val[3]))]
    result
end

def _reduce_11(val, _values, result)
 result = [:memory, val[0].new(val[2].last, 0)]
    result
end

def _reduce_12(val, _values, result)
 result = [:memory, val[0].new(val[2].last, Integer(val[4]))]
    result
end

def _reduce_13(val, _values, result)
 result = [:memory, val[0].new(val[2].last, -Integer(val[4]))]
    result
end

def _reduce_14(val, _values, result)
 result = Fisk::M64
    result
end

def _reduce_15(val, _values, result)
 result = Fisk::M32
    result
end

def _reduce_16(val, _values, result)
 result = Fisk::M16
    result
end

def _reduce_17(val, _values, result)
 result = Fisk::M8
    result
end

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
end   # module ASMREPL
